# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
#  email_provider_username: <%= ENV["GMAIL_USERNAME"] %>
#  email_provider_password: <%= ENV["GMAIL_PASSWORD"] %>
  secret_key_base: c4639aff39212df0e31b163e12a5202c182f57b80f0dcf754e65cdfdd2919dcc034570f63586764939371fc74a8a6d5eb44368e08d4b7dd93dc1465babc36a79
  http_auth_login: <%= ENV["http_auth_login"] %>
  http_auth_password: <%= ENV["http_auth_password"] %>
  jabber_user: <%= ENV["jabber_user"] %>

test:
  secret_key_base: 2d5964a76626ea85411a4e0d5ef11b383620cb426fda03a2cdc7f3f490b46d5f4ffe7a0547039abdfe2732e566eda6f59f0a7141f128e132855e7bc6356bbdec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  http_auth_login: <%= ENV["http_auth_login"] %>
  http_auth_password: <%= ENV["http_auth_password"] %>
  jabber_user: <%= ENV["jabber_user"] %>
